# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mild Road Trip
email: info@mildroadtrip.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about planning road trips that take less time than 
  watching a movie and cost less than a dinner date.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mildroadtrip.com" # the base hostname & protocol for your site
enforce_ssl: www.mildroadtrip.com # without any protocol
twitter_username: MildRoadTrip
instagram_username: MildRoadTrip

# Build settings
markdown: kramdown
